### ISSUE TITLE
In light mode, the party is not shown on the map

### ISSUE THREAD

**Issue by tijnfaas** [sergesarapov/4ad-companion#2]
When light mode is activated, the party is not visible on the map. In dark mode it is.
It is also possible to place the party on the map in light mode, but it is not shown (in dark mode the party is visible on the place it is placed in light mode).

**Comment by sergesarapov** [comment]
I will change colour of the icon with the next update, good catch! Right now it's also visible, but only if you place a party in a drawn dungeon.
